import Head from "next/head";
import axios from "axios";
import { Video } from "../types";
import VideoCard from "../components/VideoCard";
import NoResults from "../components/NoResults";

interface IProps {
  videos: Video[];
}

const Home = ({ videos }: IProps) => {
  return (
    <div>
      <Head>
        <title>TikTok</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col gap-10 videos h-full">
        {videos.length ? (
          videos?.map((video: Video) => (
            <VideoCard post={video} key={video._id} isShowingOnHome />
          ))
        ) : (
          <NoResults text={`No Videos`} />
        )}
      </div>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  let { data } = await axios.get(
    `${process.env.NEXT_PUBLIC_BASE_URL}/api/post`
  );
  return {
    props: {
      videos: data,
    },
  };
};
